name: Create release tag and release note.

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - release_note_test

jobs:
  release-note:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # タグ名を生成する
      - name: Create release tag
        id: release_tag
        run: |
          release_version=$(echo ${{ github.event.pull_request.head.ref }} | sed -E 's/^(release|hotfix)\///')
          echo "release_tag=$release_version" >> $GITHUB_OUTPUT
        shell: bash

      # リリースノートの本文を生成する
      - name: Create release note body
        uses: actions/github-script@v6
        id: release_note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            const { execSync } = require("child_process");
            const release_note = execSync("python .github/workflows/create_release_note_body.py").toString().trim();
            core.setOutput("release_note", release_note);

      # タグを切り、リリースノートを生成する
      - name: Create Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\", \"name\": \"${{ steps.release_tag.outputs.release_tag }}\", \"body\": \"${{ steps.release_note.outputs.release_note }}\", \"target_commitish\": \"master\" }" \
            https://api.github.com/repos/${{ github.repository }}/releases

  # リリースノートの本文はリリースissueから取得しているため、issue削除は必ずリリースノート生成後に行う
  close-issue:
    needs: [release-note]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # needsで指定したジョブの成功・失敗に関わらず完了後に実行させる
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: close release issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: ${{github.event.pull_request.head.ref}}
        run: python .github/workflows/close_release_issue.py