name: Create release tag and release note.

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - release_note_test

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

    # リリースノートの本文を生成する
      - name: Set release note output
        uses: actions/github-script@v6
        id: release_note
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            const { execSync } = require("child_process");
            const release_note = execSync("python .github/workflows/generate_release_note.py").toString().trim();
            core.setOutput("release_note", release_note);

      # タグを切り、リリースノートを作成する
      - name: Create Release
        run: |
          release_tag=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/^release\///')
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${release_tag}\", \"name\": \"${release_tag}\", \"body\": \"${{ steps.release_note.outputs.release_note }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases