name: Create release tag and release note.

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - release_note_test

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # タグ名を生成する
      - name: Generate release tag
        id: release_tag
        run: |
          release_version=$(echo ${{ github.event.pull_request.head.ref }} | sed -E 's/^(release|hotfix)\///')
          echo "release_tag=$release_version" >> $GITHUB_OUTPUT
        shell: bash

      # リリースノートの本文を生成する
      - name: Generate release note body
        uses: actions/github-script@v6
        id: release_note
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            const { execSync } = require("child_process");
            try {
              const options = { encoding: 'utf-8', stdio: 'inherit' };
              const release_note = execSync("python .github/workflows/generate_release_note.py", options).toString().trim();
              core.setOutput("release_note", release_note);
            } catch (error) {
              console.error("Error executing script:", error.stderr.toString());
              core.setFailed("Failed to generate release note");
            }

      # タグを切り、リリースノートを生成する
      - name: Create Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\", \"name\": \"${{ steps.release_tag.outputs.release_tag }}\", \"body\": \"${{ steps.release_note.outputs.release_note }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases